services:
  react-app:
    image: node:lts-alpine3.23
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev -- --host"
    tty: true